/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/3D EXPOSITOR ADEO.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.39, -0.04, 0.2]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0}
      >
        <group position={[-401.52, -225.34, -3.7]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["TQ_ARD-geom"].geometry}
            material={materials.TQ_ARD_front}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["TQ_ARD-geom_1"].geometry}
            material={materials.TQ_ARD_back}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["TQ_ARD-geom_2"].geometry}
            material={materials.TQ_ARD_edge}
          />
        </group>
      </group>
      <group
        position={[-0.41, -0.04, 0.14]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0}
      >
        <group position={[424.81, -135.37, -17.67]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["TQ_ARD_D2-geom"].geometry}
            material={materials.TQ_ARD_D2_front}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["TQ_ARD_D2-geom_1"].geometry}
            material={materials.TQ_ARD_D2_back}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["TQ_ARD_D2-geom_2"].geometry}
            material={materials.TQ_ARD_D2_edge}
          />
        </group>
      </group>
      <group
        position={[-0.41, -0.04, 1.05]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0}
      >
        <group position={[407.79, -1193.38, -151.88]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["TQ_ARD_D3-geom"].geometry}
            material={materials.TQ_ARD_D3_front}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["TQ_ARD_D3-geom_1"].geometry}
            material={materials.TQ_ARD_D3_back}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["TQ_ARD_D3-geom_2"].geometry}
            material={materials.TQ_ARD_D3_edge}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3D EXPOSITOR ADEO.gltf");